services:
  - name: task-manager-api
    type: web
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: PORT
        value: 3000
    branch: develop
    autoDeploy: true
    plan: free
    runtime: node